"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['lat2cyr.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'iconfile': 'lat2cyr.icns',
           'plist': {'CFBundleName': 'Lat2Cyr',
                     # must be in X.X.X format
                     'CFBundleShortVersionString': '0.3.1',
                     'CFBundleVersion': '0.3.1',
                     'CFBundleIdentifier': 'com.mihail.lat2cyr',  # optional
                     'NSHumanReadableCopyright': '@ Me 2014',  # optional
                     # optional - English is default
                     'CFBundleDevelopmentRegion': 'English',
                     }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
